name: increment
description: A 32 bit auto-increment used to distinguish requests/responses by a 'requestID' claim

version: 2.0.4
homepage: https://github.com/Moonspeaker/increment

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: